export const destinations = [
  '2mee',
  'AB Smartly',
  'Algolia Insights',
  'Apptimize',
  'Criteo Offline Conversions',
  'CustomFit.ai',
  'Experiments by Growthhackers',
  'Freshmarketer',
  'Adikteev',
  'AdLearn Open Platform',
  'AdQuick',
  'AdRoll',
  'AppNexus',
  'Bing Ads',
  'DoubleClick Floodlight',
];

export const sources = [
  'Facebook Ads',
  'ProveSource',
  'Amplitude Cohorts',
  'Looker',
  'Aircall',
  'Mandrill',
  'Marketo',
  'Sendgrid',
  'Factual Engine',
  'HEROW',
  'Foursquare Pilgrim',
  'Radar',
  'LaunchDarkly',
  'Chatlio',
  'Android',
  'iOS',
  'Kotlin (Android)',
  'React Native',
  'Swift',
  'Xamarin',
  'Stripe',
  'Twilio',
];
